language: generic
sudo: required 
services: 
  - docker
branches:
  only:
    - master
cache: false
script:
  - 'docker-compose pull'
  - "docker-compose run -e DANGER_GITHUB_API_TOKEN=$DANGER_GITHUB_API_TOKEN -e TRAVIS=$TRAVIS -e CI=$CI -e HAS_JOSH_K_SEAL_OF_APPROVAL=$HAS_JOSH_K_SEAL_OF_APPROVAL -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG test npm run $TEST_SUITE"
env:
  - TEST_SUITE=lint
  - TEST_SUITE=jest
  - TEST_SUITE=nightwatch
  - TEST_SUITE=wdio
  - TEST_SUITE=danger
jobs:
  include:
    - stage: build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "ryanthemanuel" --password-stdin
        - docker-compose build
        - docker-compose push
    - stage: release terra-node
      script:
        - docker build -t ryanthemanuel/terra-node:latest --file ./config/docker/Dockerfile ./config/docker
        - docker push ryanthemanuel/terra-node:latest
      if: NOT env(TRAVIS_PULL_REQUEST)
    - stage: release snapshot of terra-node
      script:
        - "docker build -t ryanthemanuel/terra-node:$TRAVIS_PULL_REQUEST_BRANCH --file ./config/docker/Dockerfile" ./config/docker
        - "docker push ryanthemanuel/terra-node:$TRAVIS_PULL_REQUEST_BRANCH"
      if: env(TRAVIS_PULL_REQUEST)
stages:
  - build
  - test
  - release terra-node
  - release snapshot of terra-node
