language: generic
sudo: required 
services: 
  - docker
branches:
  only:
    - master
cache: false
script:
  - 'cp ./config/docker/ci-docker-compose.yml ./docker-compose.yml'
  - 'docker-compose pull'
  - "docker-compose run -e DANGER_GITHUB_API_TOKEN=$DANGER_GITHUB_API_TOKEN -e TRAVIS=$TRAVIS -e CI=$CI -e HAS_JOSH_K_SEAL_OF_APPROVAL=$HAS_JOSH_K_SEAL_OF_APPROVAL -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG test npm run $TEST_SUITE"
env:
  global:
    - DOCKER_IMAGE='ryanthemanuel/terra-toolkit'
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=jest
    - TEST_SUITE=nightwatch
    - TEST_SUITE=wdio
    - TEST_SUITE=danger
jobs:
  include:
    - stage: build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "ryanthemanuel" --password-stdin
        - 'cp ./config/docker/ci-docker-compose.yml ./docker-compose.yml'
        - docker-compose build
        - docker-compose push
    - stage: release terra-node
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "ryanthemanuel" --password-stdin
        - 'TAG=latest docker-compose -f ./config/docker/build-docker-compose.yml build'
        - 'TAG=latest docker-compose -f ./config/docker/build-docker-compose.yml push'
      if: type != pull_request
    - stage: release snapshot of terra-node
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "ryanthemanuel" --password-stdin
        - "TAG=$TRAVIS_PULL_REQUEST_BRANCH docker-compose -f ./config/docker/build-docker-compose.yml build"
        - "TAG=$TRAVIS_PULL_REQUEST_BRANCH docker-compose -f ./config/docker/build-docker-compose.yml push"
      if: type = pull_request
stages:
  - build
  - test
  - release terra-node
  - release snapshot of terra-node
